### PR TITLE
Clean up user model for multiple providers

### PR DESCRIPTION
**Pull request by aragilar**
Provider profiles will be stored in their own space, with required
information extracted from from the profile as put in the top-level
area.

New providers need to put a file in `src/auth_providers`, which has a
function which returns a passport strategy ready for use, including
parsing profile information to create/update a user in the database.

@Denubis To match this to the existing setup, you'll need to export the following new environment variables:
* `CONDUCTOR_AUTH_PROVIDERS=datacentral`
* `DATACENTRAL_CLIENT_ID` and `DATACENTRAL_CLIENT_SECRET`
* `HAVE_DATACENTRAL_MANAGE_ROLES=true`

Once you've made the changes as needed to the dev system, can you merge this (as otherwise bouncing without those changes will cause the conductor to error stating it's not been set up correctly)? 

@stevecassidy You'll probably want to rebase your docker-compose PR on top of this.

### CODE REVIEW

**Comment by aragilar** [comment]
Ah, this is failing as we need a dummy provider for testing. I'll copy over the config for Data Central, but we likely should use a username/password provider.

**Comment by Denubis** [comment]
Send me the ID and secret on slack/lastpass, please?

**Comment by Denubis** [comment]
@stevecassidy Approve-for-Merge this after you've pulled the necessary changes over to your branch?

**Pull request merged**
